### ISSUE TITLE
Question: Should is4 & is4ui build without additions?

### ISSUE THREAD

**Issue by beavel** [IdentityServer/IdentityServer4.Templates#1]
I was spinning up a new project and thought I would try out the new templates. I tried the following and couldn't build.

```
mkdir IdentityServerTest
pushd IdentityServerTest
dotnet new is4
dotnet new is4ui

dotnet restore
dotnet build
```

The errors made it look like MVC was missing so I then added MVC and it built without issue.

```
dotnet add package Microsoft.AspNetCore.Mvc -v 1.1.2
dotnet restore
dotnet build
```

Not sure if the expectation was to just add the UI files and require the dev to add dependencies or if it should handle the dependency addition.

I tried reading through the documentation for templating and didn't see a clear path on how to simply add the equivalent of the `dotnet add package` to the process. After reading, I was wondering if making the UI piece an optional parameter to is4 could help solve adding it without forcing MVC on is4. I know the tooling is really new so I was just wondering.

**Comment by leastprivilege** [comment]
You are right - you need to add MVC and StaticFiles manually. 

I read somewhere about post actions - so maybe that is the right way to add those dependencies. The new templating engine is pretty new, so I though we'll wait a bit until they catch up with features and docs - and let the templates be simple for the time being.

**Comment by leastprivilege** [comment]
I added the necessary metadata to add the packages. But this is not support in the v1 tooling yet.
