### ISSUE TITLE
Provide extension method (or template) for self-contained app w/ AspId

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.Templates#16]
As per suggestion from @chrisklug

**Comment by brockallen** [comment]
Or possibly even without AspId -- more of a dev IdSvr for local dev, so that clients and scope setup.

Something to make it less config... but might not be possible.

**Comment by leastprivilege** [comment]
who is this @ChrisKlug ?

**Comment by brockallen** [comment]
I think the templates now address this. So whoever this @ChrisKlug is, perhaps he can check them out.

**Comment by ChrisKlug** [comment]
Sorry, I've been out of it for a while. Where am I looking? Can't see any commits connected to this issue...

**Comment by brockallen** [comment]
This: https://leastprivilege.com/2017/11/22/updated-templates-for-identityserver4/

**Comment by ChrisKlug** [comment]
Nice! I approve! ;)

Looks very easy to use! Going to make my life a lot easier! I'll definitely use it for my demo in Poland in a few weeks! ;)
