### ISSUE TITLE
Can't create template - stuck at trying to seed.

### ISSUE THREAD

**Issue by gordon-matt** [IdentityServer/IdentityServer4.Templates#22]
I'm running "**dotnet new is4ef**" and it gets stuck when trying to seed. The output in the package manager console is as follows:

```
dotnet new is4ef --force
The template "IdentityServer4 with Entity Framework Stores" was created successfully.
Processing post-creation actions...
Template is configured to run the following action:
Description: 
Manual instructions: Seeds the initial database
Actual command: dotnet run /seed
Do you want to run this action (Y|N)?
```

It won't allow me to type Y or N and I have to use the "Stop command execution" button.

Note: this is my first time using a "dotnet new template" - so I am not familiar with them and perhaps I am doing something wrong here.

**Comment by gordon-matt** [comment]
Thanks for the response. `-- force` was used on my second attempt. I think it was necessary in order to overwrite existing files. In any case, ignore it because the first attempt was exactly the same even without using `-- force`

**Comment by leastprivilege** [comment]
Is that on Windows?

anyways - you can see manually by running

`dotnet run /seed` after you exit the template engine.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by robertye112** [comment]
I get the same problem. Running dotnet run /seed manually as mentioned gives hundreds of errors like: IdentityServer4.Templates-dev\src\IdentityServer4Admin\obj\Debug\netcoreapp2.1\IdentityServer4Admin.RazorAssemblyInfo.cs(14,54): error CS0234: The type or namespace name 'RelatedAssemblyAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts' (are you missing an assembly reference?) [D:\QS\QS.csproj]

**Comment by gordon-matt** [comment]
FYI - I've been busy with other projects, so haven't had a chance yet to see if it's solved for me either. So while I understand these issue can't be kept open forever, just note that it could still be a problem, and apparently it seems to be for you, @robertye112 .

**Comment by robertye112** [comment]
good news. I just solved it. The folder has to be empty and I didn't know
that. I had other cs files from other projects in there being built

**Comment by mirikerstein** [comment]
I'm having this issue. Any suggestions? The console just 'hangs' by the Y | N bit.

**Comment by deegraham** [comment]
Same issue here

**Comment by nuprinX** [comment]
For what it's worth, I had this issue. Trying to run the **dotnet new is4ef** in the **Package Manager Console in VS 2019**. It didn't matter if I used **--force** or if the directory was empty, it would always hang at the **Do you want to run this action (Y|N)?** prompt. 

I ended up executing the dotnet new is4ef in VS Code, and it worked without a hitch.
