### ISSUE TITLE
dotnet new is4admin error

### ISSUE THREAD

**Issue by zacpwhite** [IdentityServer/IdentityServer4.Templates#24]
I've installed the latest templates using `dotnet new -i identityserver4.templates` and am getting the following error when trying to generate the new is4admin template:
```
~/> dotnet new is4admin
Object reference not set to an instance of an object.
```

**Comment by westerncj** [comment]
I'm getting the same error as well @zacpwhite.

**Comment by richardblewett** [comment]
what platform are you running this on?

**Comment by zacpwhite** [comment]
macOS. Here is the output of `dotnet --info`:

```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

**Comment by leastprivilege** [comment]
thanks for reporting. I will look into it.

**Comment by leastprivilege** [comment]
opened an issue with Microsoft since the same template works just fine on Windows

https://github.com/dotnet/templating/issues/1397

**Comment by geminiyellow** [comment]
not working, i copy the cli from README, noting happen.
and i try the `mvc`, it working.

```
➜  Sources dotnet --info
.NET コマンド ライン ツール (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by leastprivilege** [comment]
We'll update the template today or tomorrow to fix this problem.

**Comment by geminiyellow** [comment]
@leastprivilege thank you.

**Comment by leastprivilege** [comment]
I just pushed an upated. Please give it a try.

**Comment by zacpwhite** [comment]
I can confirm that the updated template is working correctly on macOS. Thank you @leastprivilege!

**Comment by geminiyellow** [comment]
me too, thank you @leastprivilege . good job 👍

**Comment by scottbrady91** [comment]
Thank @SamuelDBridgman for this one 🥇
