### ISSUE TITLE
template is4admin change tables schema error

### ISSUE THREAD

**Issue by xgluxv** [IdentityServer/IdentityServer4.Templates#25]
Hi,
I create an new project for is4admin. and change default db to sql server and change tables schema like this: 
```
.AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                    options.DefaultSchema = "NewSchemaName";
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.DefaultSchema = "NewSchemaName";
                    // options.TokenCleanupInterval = 15; // interval in seconds. 15 seconds useful for debugging
                });
```
Migrations new db, and run it, report an error:

 > System.Data.SqlClient.SqlException: 'Invalid object name 'IdentityResources'.'

from `app.UseAdminUI();`
Is this admin ui can't change tables name ?

**Comment by andrewclymer** [comment]
CommunityEdition does not support any other database other than the SQLite that it ships with.  The role of CommunityEdition is just to get you up and running with IdentityServer to test client integration scenarios.  Apologies for any misunderstanding of its role

If you want to test against more production ready environments we can provide a trial key for the full product.  www.identityserver.com/products
