### ISSUE TITLE
Unable to run is4admin template: Cannot resolve scoped service 'IdentityExpress.Manager.BusinessLogic.Interfaces.Services.ILicenseService' from root provider.

### ISSUE THREAD

**Issue by nathan-hitchman** [IdentityServer/IdentityServer4.Templates#30]
After installing the identityserver4.templates and then creating a new project with dotnet new is4admin, when I run the project the following error is displayed:

An error occurred while starting the application.
InvalidOperationException: Cannot resolve scoped service 'IdentityExpress.Manager.BusinessLogic.Interfaces.Services.ILicenseService' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)

**InvalidOperationException: Cannot resolve scoped service 'IdentityExpress.Manager.BusinessLogic.Interfaces.Services.ILicenseService' from root provider.**
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by leastprivilege** [comment]
pinging @scottbrady91

**Comment by brockallen** [comment]
any update

**Comment by piyey** [comment]
I had to use this in my Program Class in WebHost (IWebHostBuilder)

`UseDefaultServiceProvider(opt => opt.ValidateScopes = false)`

**Comment by leastprivilege** [comment]
That's weird - let's ping @scottbrady91 again...

**Comment by scottbrady91** [comment]
Yeah, I'm getting the same error. How has this broken when there have been no code changes?

**Comment by leastprivilege** [comment]
Is that on 2.1 ? 

https://stackoverflow.com/questions/50222688/di-exception-for-indentityserver4-after-install-core-2-1-sdk

Seems MS has turned on DI validation by default now. There is a hidden bug in the AdminUI DI setup I guess.

**Comment by scottbrady91** [comment]
Yeah, I didn't manually install 2.1. Thanks, Visual Studio!

**Comment by leastprivilege** [comment]
@richardblewett Rich, there seems to be a bug in how you setup DI. This error typically means you are resolving a scoped dependency somewhere while not being in a scoped context. This turns your dependency into a singleton.

It seems that starting with 2.1 MS turns on validation by default - hence the exception. Could you please fix and version the nuget, so we can create new templates.

**Comment by leastprivilege** [comment]
Update nuget pushed. 

Thanks for reporting!

**Comment by nathan-hitchman** [comment]
Thanks all.
