### ISSUE TITLE
Using TEXT data type in dotnet new is4ef

### ISSUE THREAD

**Issue by aboyaniv** [IdentityServer/IdentityServer4.Templates#31]
hello.

The SQL scripts "PersistedGrantDb.sql" , "ConfigurationDb.sql"  and the migration plans are using "TEXT" columns type.

In SQL server 2016 "TEXT" Datatype id Deprecated and need to be replaced to varchar(max).

**Comment by brockallen** [comment]
IIRC, that's what the EF migration script emits. Perhaps this should be raised with the EF team?

**Comment by brockallen** [comment]
ah, good to hear. i'll close this and track over here: https://github.com/IdentityServer/IdentityServer4/issues/2300
