### ISSUE TITLE
issue with ProcessWindowsLoginAsync

### ISSUE THREAD

**Issue by dotconsulting** [IdentityServer/IdentityServer4.Templates#34]
The constant used for the scheme during sign-in action is not correct. Instead of IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme it must be IdentityConstants.ExternalScheme otherwise ExternalLoginCallBack will fail.  In my case it worked.  Can you confirm this is the correct fix?

**Comment by leastprivilege** [comment]
For which template?

**Comment by dotconsulting** [comment]
Hi!

In the admin template for me. I didn’t check the others. 
Maybe the QuickStart part must be updated with the one from the QuickStart repository?
Thanks!
Bertrand Giot.

**Comment by brockallen** [comment]
Fixed on dev.
