### ISSUE TITLE
IdentityServer4 with ASP.NET 2.1.0

### ISSUE THREAD

**Issue by aborderon** [IdentityServer/IdentityServer4.Templates#35]
Have you planned to support ASP.NET Core 2.1.0 in the generation of IdentityServer4 templates with Dotnet Cli as well as the generation of templates (mvc, webapi ...)?

Because we have a compatibility gap between the generation of IdentityServer and a Web API with Dotnet Cli.

**Comment by leastprivilege** [comment]
With the next release of IdentityServer we will update the templates as well.

**Comment by aborderon** [comment]
Ok, thanks for this feedback.
