### ISSUE TITLE
is4aspid assumes sqlite

### ISSUE THREAD

**Issue by ckpearson** [IdentityServer/IdentityServer4.Templates#44]
Just spent a little while trying to do battle with the seed process owing to this, as switching the `UseSqllite` calls to `UseSqlServer` weren't enough, as the initial migration specifies sqlite annotations for identity, but not the MS-SQL ones.

It would be good if the template selection either allowed you to pick between the two / if there were separate templates as not everyone is automatically going to be wanting to use sqlite when utilising a template, furthermore, the documentation that references these templates make no mention of this caveat.

**Comment by brockallen** [comment]
Yes, this is an aspect of how EF Core's migrations work. If you change your DB provider you'd need to re-gen migrations.

**Comment by ckpearson** [comment]
@brockallen that's fine, but there's nothing to re-gen the migration from given it's using a structure specific for the asp.net identity types without any real code-first mapping or config to infer it from, the migration file itself is used as the truth in the template :/
