### ISSUE TITLE
Missing configuration

### ISSUE THREAD

**Issue by darianferrer** [IdentityServer/IdentityServer4.Templates#46]
Hi,

I was trying to setup an idp using the is4admin template, and right now is throwing an exception because a missing configuration, related to issue [2909](https://github.com/IdentityServer/IdentityServer4/issues/2909)

`services.AddIdentityServer(options =>
{
                options.UserInteraction = new UserInteractionOptions()
                {
                    LogoutUrl = "/account/logout",
                    LoginUrl = "/account/login",
                    LoginReturnUrlParameter = "returnUrl"
                };
            })`

After putting that snipet of code, everything worked ok.

**Comment by leastprivilege** [comment]
@scottbrady

**Comment by brockallen** [comment]
merged apparently
