### ISSUE TITLE
Add Visual Studio Templates

### ISSUE THREAD

**Issue by reiniellematt** [IdentityServer/IdentityServer4.Templates#55]
There's no problem with the templates when creating a project in the command line. It's just that it's sometimes a hassle to create a project then opening it in VS for VS users. I hope to find an official extension for VS for creating new projects with Identity Server.

P.S. I opened the issue here since it's a concern with templates rather than Identity Server itself.

**Comment by leastprivilege** [comment]
We looked at it and it not straightforward to do that. Microsoft will have some templates in ASP.NET Core 3 that include IdentityServer though.
