### ISSUE TITLE
Does RSK.Audit 2.0.0 even exist?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4.Templates#66]
https://github.com/IdentityServer/IdentityServer4.Templates/blob/465cc1d427227bd7abcfd9ae49e38f1a44cf1dee/src/IdentityServer4Admin/IdentityServer4Admin.csproj#L20-L21

https://www.nuget.org/packages/RSK.Audit.EF/1.1.0-preview1#show-github-usage

![image](https://user-images.githubusercontent.com/2934507/66220350-7b508900-e692-11e9-889d-6f9c14212ee4.png)

![image](https://user-images.githubusercontent.com/2934507/66220386-886d7800-e692-11e9-86f7-8ce44b7eb30f.png)

**Comment by leastprivilege** [comment]
@scottbrady91

**Comment by scottbrady91** [comment]
Yes, but it is archived. Are you having issues resolving it?

**Comment by VictorioBerra** [comment]
@scottbrady91 No, I was doing some investigation to see what other Core 3 projects were doing and saw that and found it odd.
