### ISSUE TITLE
dotnet new still installing asp.net core 2.1 templates

### ISSUE THREAD

**Issue by lenardchristopher** [IdentityServer/IdentityServer4.Templates#67]
**Expected**
Generating a IdentityServer4 project using IdentityServer4.Templates with `dotnet new` should return ASP.NET Core 3.0 projects.

**Actual**
IdentityServer4.Templates and `dotnet new` command generates ASP.NET Core 2.1 templates.

**Repo Steps**
1. Download and install .NET Core 3.0 SDK
2. Install Identity Server 4 Templates using `dotnet new -i IdentityServer4.Templates`
3. Generate a new project using the templates (Example: `dotnet new is4inmem`)
4. Inspect the new project's _csproj_ file and see it is targeting ASP.NET Core 2.1 and _Startup.cs_ is still configured for 2.1.

**Comment by leastprivilege** [comment]
Works for me.

Maybe do a 

dotnet new --debug:reinit

and make sure you install the 3.0 version of the templates

dotnet new --install IdentityServer4.Templates::3.0.0

**Comment by bchewy** [comment]
My .net version is 2.2.401 and I'm getting the same issue. I can't do either
`dotnet new -i IdentityServer4.Templates` & with the 3.0 version; I also did debug and reinit.

Please advise @leastprivilege

**Comment by bchewy** [comment]
`dotnet new --debug:reinit`
worked for me on .net 2.2. Just had to let others know!
