### ISSUE TITLE
Updating UI .sh missing in IdentityServer4InMem template 

### ISSUE THREAD

**Issue by enmesarru** [IdentityServer/IdentityServer4.Templates#68]
There is not .sh script to update ui for unix-like systems but it exists for windows as .ps script.

Repo:
https://github.com/IdentityServer/IdentityServer4.Templates/tree/master/src/IdentityServer4InMem

Should we put this .sh into IdentityServer4InMem repository ?
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/getmaster.sh

**Comment by leastprivilege** [comment]
The script is really only used by us when publishing the templates. If I could exclude it from the nuget, I would.
