### ISSUE TITLE
SeedData doesnt fill ASPNetUserClaims table, after create is4aspid template (Sqlserver)

### ISSUE THREAD

**Issue by Ksantacr** [IdentityServer/IdentityServer4.Templates#69]
After run

`dotnet net new is4aspid`
and
`dotnet run /seed`

I check ASPNetUserClaims is empty. Please add

`.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)` 

in file Data/Migrations/20180109192453_CreateIdentitySchema.cs

**Comment by GioviQ** [comment]
The template uses SQLite.
