### ISSUE TITLE
zsh: no matches found: identityserver4.templates::*

### ISSUE THREAD

**Issue by oscarwest** [IdentityServer/IdentityServer4.Templates#7]
When running command:
```dotnet new -i identityserver4.templates::*```

Works fine if you switch to bash first:
```
exec bash
dotnet new -i identityserver4.templates::*
```

After installing the templates initialization works fine in zsh:

`dotnet new is4inmem`

**Comment by brockallen** [comment]
Not sure -- @mlorbetske?

**Comment by mlorbetske** [comment]
If I recall correctly, for zsh, the argument to the install option must be quoted or the exact id/version pair, otherwise wildcard expansion kicks in
