### ISSUE TITLE
Redirect to http://localhost:5000/grants not working

### ISSUE THREAD

**Issue by GioviQ** [IdentityServer/IdentityServer4.Templates#72]
### Issue / Steps to reproduce the problem

dotnet new is4aspid or dotnet new is4ef with seed

Open project with Visual Studio 2019
 run on IIS
click on http://localhost:5000/grants
 after login you are not redirect

**Comment by leastprivilege** [comment]
I just tried that on my machine and it works. I also update the templates recently. Maybe re-install them to see if that makes a change.

**Comment by GioviQ** [comment]
I discovered the same issue on another project using IdentityServer: see my PR https://github.com/enkodellc/blazorboilerplate/pull/195

Anyway it is not related to IdentityServer, but login and cookies in general.

**Comment by leastprivilege** [comment]
OK. Good.
