### ISSUE TITLE
Support for IdentityServer4 (4.0.2)

### ISSUE THREAD

**Issue by blaiseliu** [IdentityServer/IdentityServer4.Templates#81]
These templates can only create 3.1.3 version IdentityServer4.
![image](https://user-images.githubusercontent.com/2326117/87084078-a193ee00-c1fb-11ea-9928-2c51df6b9ff4.png)

What is our schedule to support the latest IdentityServer?

**Comment by leastprivilege** [comment]
All templates besides the one with the AdminUI have been updated. More info? @scottbrady91

**Comment by scottbrady91** [comment]
We're hoping to have AdminUI support v4 in September.
