### ISSUE TITLE
is4aspid Template causes Local Authentication to not Redirect to Client Application following successful Login

### ISSUE THREAD

**Issue by HuntJason** [IdentityServer/IdentityServer4.Templates#82]
Steps to reproduce:

1. Install from template: `dotnet new is4aspid`
2. [Install UI Updates](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI)

Use Local Login with client that was successfully able to log in previously.

Application no longer redirects back to Client Application.

I was able to discover that the issue was related to the template leaving the `.AddAspNetIdentity<ApplicationUser>()` line in the Startup.ConfigureServices method. Removing that line (to be like that is in the [Demo Site](https://demo.identityserver.io/) resolves the problem and returns the user to the client application following successful Local Authentication login.

**Comment by HuntJason** [comment]
I should add that step 2 included updating the nuget packages for the project.

**Comment by leastprivilege** [comment]
> Install UI Updates

Why? The template comes with the lastest UI.
